name: Plugin Unit Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cd plugin/ && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Cd plugin
      run: cd plugin/ 
    - name: Generate key
      run: cd plugin/ && php artisan key:generate
    - name: Directory Permissions
      run: cd plugin/ &&  chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cd plugin/
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: cd plugin/ && vendor/bin/phpunit
